spring.application.name=demo
# Tell Spring Boot where the database is
spring.datasource.url=jdbc:mysql://localhost:3306/url_shortener?serverTimezone=UTC
spring.datasource.username=url_admin
spring.datasource.password=password123

# This is the magic line that tells Spring to auto-create your tables!
spring.jpa.hibernate.ddl-auto=update

# Show the SQL in the console so you can see what Spring is doing behind the scenes
spring.jpa.show-sql=true